# Copyright 2021 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build led crkbd'
on:
  - workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    with:
      keyboard: '["crkbd"]'
      alphas: '["default"]'
      nav: '["default"]'
      clipboard: '["default"]'
      layers: '["default"]'
